packages:
  - 'packages/**'

catalog:
  '@opensig/opendesign': '0.0.78'
  '@vueuse/core': '10.11.1'
  'aos': '^2.3.4'
  'vue': '^3.5.13'
  'vue-i18n': 'latest'
  'vue-router': '4.5.1'
  '@tsconfig/node22': '^22.0.2'
  '@types/aos': '^3.0.4'
  '@types/node': '^22.15.33'
  '@vitejs/plugin-vue': '^5.2.3'
  '@vitejs/plugin-vue-jsx': '^1.3.10'
  '@vue/tsconfig': '^0.7.0'
  'sass': '^1.51.0'
  'typescript': '~5.8.3'
  'vite': '^6.3.5'
  'vue-tsc': '^2.2.8'
  'eslint': '^8.19.0'
  'prettier': '^2.7.1'
